### ISSUE TITLE
what is source account password?

### ISSUE THREAD

**Issue by chiptus** [cryptiumlabs/backerei#11]
Is it the payer private key? isn't there a safer way to do this?

How is backerei pays the delegates?

**Comment by cwgoes** [comment]
You can select any account from which to pay rewards - the address specified in the configuration is the hash of a public key, with which the Tezos client can look up the private key. Backerei never stores private keys and does not handle signing logic directly (it calls `tezos-client`).

**Comment by chiptus** [comment]
i understand, so what is the source account address? when I'm doing dry runs i can input whatever

**Comment by cwgoes** [comment]
The source account address is the address Backerei will instruct the Tezos client to pay rewards from. In dry run mode, no transactions will be sent, so this address doesn't matter (although Backerei may still check if the balance is sufficient).

**Comment by chiptus** [comment]
Isn't it the address we configure with --from?

**Comment by cwgoes** [comment]
Yes, exactly, which is written as `fromAddress: KT1....` in `~/.backerei.yaml`.

**Comment by chiptus** [comment]
I'm sorry, the title was wrong
when I run `backerei payout`, I'm asked for a source account password. What do I need to write here?

**Comment by chiptus** [comment]
ok, because when I give the password for the account, backerei doesn't log anything and it doesn't seem like it created any transactions. IMO it should log that payments where made and how much.

**Comment by chiptus** [comment]
maybe it happens because the .json file already has the data for the cycles so it skips them? how does backerei knows if it should make a payment or skip the cycle?

**Comment by chiptus** [comment]
what can be the reason nothing happens when I do `--no-dry-run`?

**Comment by cwgoes** [comment]
Likely because you have no transactions to send. If `backerei payout` doesn't print out any payments-to-be-made, `backerei payout --no-dry-run` will not send any payments.

**Comment by chiptus** [comment]
Great, thanks for clearing that out. You can close the issue for now

**Comment by jrhite** [comment]
@cwgoes sorry to hash this up, but i'm a little confused as well. i have a node that uses a remote-signer. i've imported the secret keys for both the main baking TZ1 account and the payment TZ1 account of the KT1 account that will make the actual payments into the node (meaning the node knows where to find the remote signer to have the signing done)...

i'm pointing backerei to my node, so what password do i need to enter into backerei? the password for the secret key of the payment TZ1 account?

thanks!

**Comment by cwgoes** [comment]
That depends on the behaviour of `tezos-client sign`, I haven't tried with a remote signer. You may be able to enter no password at all (just hit enter). Possibly the remote signer terminal prompt will be different and you might have to modify `backerei` not to confirm the transaction (if it is auto-confirmed).

**Comment by jrhite** [comment]
Ok, interesting.

With the remote-signer, when the remote-signer is started it prompts for
the password of every key it signs for. Next keys are imported into the
main node, so main node stores a pointer to the ip address of the remote
signer.

When, for example 'tezos-client sign 0x03 for my_baker' is called, the node
makes an rpc to the signer, gets the signature back from the signer and
returns it, no prompts for passwords.

Hmm...ok, thanks. I'll play with this a bit more and see what happens.

Thanks!

**Comment by jrhite** [comment]
I confirmed that backerei uses my local tezos-client install. When I run my local tezos-client to sign against a remote signer, I test it. Eg:

`tezos-client sign bytes 0x03 for my_payer_wallet`

the message is signed correctly.

However when running `backerei payout` it prompts for:

`Enter source account password: `

I enter nothing and then backerei does nothing. No output, nothing to debug. I'm not sure if there is an error or what because I see no output.

If I delete the .backerei.json file and rerun `backerei payout`, it prompts me again for the source account password. I just hit enter and then it goes on to create a new .backerei.json DB file.

But nothing else happens. It seems like backerei won't work with a remote-signer? Or backerei requires a password? (I've tried entering the correct password too, even though tezos-client is not prompted for it because I haven't set the --require-authentication flag on the remote signer).

Is there anywhere else I can look to troubleshoot this?

**Comment by clonesadkeanu** [comment]
> I confirmed that backerei uses my local tezos-client install. When I run my local tezos-client to sign against a remote signer, I test it. Eg:
> 
> `tezos-client sign bytes 0x03 for my_payer_wallet`
> 
> the message is signed correctly.
> 
> However when running `backerei payout` it prompts for:
> 
> `Enter source account password: `
> 
> I enter nothing and then backerei does nothing. No output, nothing to debug. I'm not sure if there is an error or what because I see no output.
> 
> If I delete the .backerei.json file and rerun `backerei payout`, it prompts me again for the source account password. I just hit enter and then it goes on to create a new .backerei.json DB file.
> 
> But nothing else happens. It seems like backerei won't work with a remote-signer? Or backerei requires a password? (I've tried entering the correct password too, even though tezos-client is not prompted for it because I haven't set the --require-authentication flag on the remote signer).
> 
> Is there anywhere else I can look to troubleshoot this?

I got the same issue.
when run `backerei payout `, it's OK. Howenver when I run `backerei payout --no-dry-run`, and input  source account password as required, nothing shown.
Anyone got the same issue, and is there any wrong in my running?
Thank you in advance!!

**Comment by clonesadkeanu** [comment]
> > I confirmed that backerei uses my local tezos-client install. When I run my local tezos-client to sign against a remote signer, I test it. Eg:
> > `tezos-client sign bytes 0x03 for my_payer_wallet`
> > the message is signed correctly.
> > However when running `backerei payout` it prompts for:
> > `Enter source account password: `
> > I enter nothing and then backerei does nothing. No output, nothing to debug. I'm not sure if there is an error or what because I see no output.
> > If I delete the .backerei.json file and rerun `backerei payout`, it prompts me again for the source account password. I just hit enter and then it goes on to create a new .backerei.json DB file.
> > But nothing else happens. It seems like backerei won't work with a remote-signer? Or backerei requires a password? (I've tried entering the correct password too, even though tezos-client is not prompted for it because I haven't set the --require-authentication flag on the remote signer).
> > Is there anywhere else I can look to troubleshoot this?
> 
> I got the same issue.
> when run `backerei payout `, it's OK. Howenver when I run `backerei payout --no-dry-run`, and input source account password as required, nothing shown.
> Anyone got the same issue, and is there any wrong in my running?
> Thank you in advance!!

Update: fixed in my case: 
- make tezos-client executable:
```
sudo ln -s /root/tezos-mainnet/tezos-client /usr/local/bin/tezos-client
sudo chmod +x /root/tezos-mainnet/tezos-client
```
Result:
```
cosmos@cosmos-testnet:/tmp# backerei payout --no-dry-run
Enter source account password:
Total payouts: 1019.138886, payout account balance: 0.000000
Balance less than total required to pay cycle, aborting
```
Hope this may help others!
