### ISSUE TITLE
backerei hangs forever

### ISSUE THREAD

**Issue by chiptus** [cryptiumlabs/backerei#18]
After fixing the yaml and revealing our public key, now the client hangs forever without sending any rewards.

**Comment by cwgoes** [comment]
Which command did you run - have you checked that `tezos-client` can sign & send transactions?

**Comment by chiptus** [comment]
yes, just did a `tezos-client transfer` and it worked.
backerei shows `Running "tezos-client ... sign bytes ... for bakepay" in a pty`, but stays there forever

**Comment by cwgoes** [comment]
Try running the comment manually and see if `tezos-client` signs the transaction successfully.

**Comment by chiptus** [comment]
i tried and it did sign it successfully, no errors from tezos-client

**Comment by chiptus** [comment]
it signs successfully, but when I try to decode it on https://kukai.app/offline-signing it didn't work. I guess there's something wrong with the bytes it tries to sign. where can we chat so I can send you the exact output without exposing it to public? are you on obisidian's bakers slack?

**Comment by issie81** [comment]
i think i have the same running no-dry run gives me

xx@payment:~/tezos$ backerei payout --no-dry-run
Enter source account password: 
Total payouts: 0.191056, payout account balance: xx
For cycle 64 delegator xx should be paid 0.191056 XTZ
Running '/home/xx/tezos/tezos-client -c /home/xx/.tezos-client/config sign bytes 0x031e3cf235638312719aff8222a1835e3629656642896b3f213a4ac0f168c2247e080000571bd249326124a9b101eb101b39515e8b356fdb009f8f35f85500d0d40b01fe0be860211931133e81111a25ed21a82a9d09c90000 for flippintacos' in a pty

here it stays forever what to do?

**Comment by cwgoes** [comment]
@chiptus Did you test running the `sign` command manually? `backerei` just produces whatever signature output `tezos-client` would produce. You shouldn't need to show me the exact output.

@issie81 I answered here - https://github.com/cryptiumlabs/backerei/issues/27#issuecomment-457960275.

**Comment by issie81** [comment]
chiptus are you running vanity address?
is there a pass set.. i did have same did (had account without pass, vanity)
made a new address (normal) and with pass after that all went good

**Comment by chiptus** [comment]
running the `sign` command manually produces a string successfully. But trying to decode it using something like https://kukai.app/offline-signing failed.

**Comment by cwgoes** [comment]
Hmm, the Tezos client & that webapp might pad the signed string differently.

**Comment by chiptus** [comment]
hmmm, osx, terminal

**Comment by cwgoes** [comment]
Possibly the code which `backerei` uses to interact with `tezos-client` through a virtual pty isn't OSX compatible.

Can you possibly try on Linux? Otherwise you could play around with the `sign` function at the bottom of `app/Payout.hs`.

**Comment by chiptus** [comment]
Thanks for the answer, I will have a look at both.

**Comment by cwgoes** [comment]
Any luck?

**Comment by cwgoes** [comment]
Closing, but reopen if you still need help debugging.

**Comment by emilnygaard** [comment]
I'm seeing the same thing. Sometime last week, backerei just stopped doing the automatic transactions, and when trying to restart it, I see that it's stuck on
`Running '/home/tezos/tezos/tezos-client -c /home/tezos/.tezos-client/config sign bytes ** for **' in a pty` 

When running the command manually it runs, and says "Signature: ***" but the transactions are never completed. 

Any ideas? :)

**Comment by cwgoes** [comment]
Are you using a remote signer, or did you change your configuration at all prior to the issue?

**Comment by emilnygaard** [comment]
Nothing changed before this stopped, and I don't think I'm using a remote signer. Everything is running on the node :)

**Comment by emilnygaard** [comment]
I manually did payouts for cycle 101 now, and changed Backerei to start with cycle 102, just to try to refresh some things - but it still get's stuck.
I also tried to update backerei by doing git pull and make clean - make build, but when running make commands now, I get:
```
Cloning 9526dbc0b07ea37f37f4753177390df10385fe83 from git@github.com:shmish111/hriemann.git
Cloning into '/home/tezos/backerei/.stack-work/downloaded/wMCsb-qHp-JV'...
Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by emilnygaard** [comment]
I've tried updating the entire node now, inlcuding backerei, and it still get's stuck on `running xxx sign bytes..`

**Comment by cwgoes** [comment]
Hmm, strange, unfortunately I don't really know where to start to help you.

Are you familiar with Haskell? Try modifying the code at the bottom of `app/Payout.hs` which handles signing (the `sign` function).
