### ISSUE TITLE
Can't get no-dry-run to work

### ISSUE THREAD

**Issue by issie81** [cryptiumlabs/backerei#19]
I have installed backerei, which seems great app. I am running into issue when going into --no-dry-run
its ask for a pass and then nothing happens, no error no pass nothing. I think it's something in the config

fromAddress: xx
fromAccountName: xx
databasePath: /home/xx/.backerei.json
fee:
  denominator: 10
  numerator: 1
cycleLength: 4096
clientPath: /home/xx/.tezos-client
clientConfigFile: /home/xx/.tezos-client/config
startingCycle: 48
host: 127.0.0.1
snapshotInterval: 256
bakerAddress: xx
port: 8732

i removed some parts for privacy... but the .tezos-client has only 3 files in it (public-key, public-key_hash and secret_keys)
also i am lost on the clientConfigFile i can't seem to find a right location (where do i need to point this out)
since payout works good i think it's just matter of small adjustment

FYI payout is being done by tz1 account it shouldn't be a problem i assume.. (it's different then baker address)

**Comment by issie81** [comment]
yeah backerei payout did calculate the rewards (if i run backerei payout now nothing happens)
i have been solo baking and the json file i see the correct rewards.. the solo baking is from cycle 48 and are released in tzscan... i was thinking maybe it's because i am solo baking but the json file says i get xx number reward (which is correct 10% value)

what are clientpath and clientconfigfile?

**Comment by cwgoes** [comment]
Client path specifies the full file path of the `tezos-client` binary.

Client config file specifies the full file path of the `tezos-client` configuration (which contains e.g. the remote node address).

**Comment by issie81** [comment]
you mean the path where the ./client-tezos to execute commands? which seems logical since with that command you can execute transactions

so that leave the config file, where is this normally situated? i looked everywhere but can't seem to find it?

also since cycle ended i did another backerei payout and get this

backerei payout
Enter source account password: 
Updating DB with estimates for cycle 63...
Updating DB with actual earnings for cycle 57...
backerei: app/Payout.hs:56:19-92: Irrefutable pattern failed for pattern [thisCycle]

**Comment by adrianbrink** [comment]
Normally the configuration file `config` for the `tezos-client` can be found here `$HOME/.tezos-client/config`.

Can you post your `backerei.yaml` file and your `config` file here.

**Comment by emilnygaard** [comment]
I'm seeing the same thing with the pattern failing on the same line of code. I have the same confog file pretty much.

**Comment by chiptus** [comment]
@issie81 seems like your clientConfigFile is wrong, it points to the node config and not to the client.
usually it's `$HOME/.tezos-client/config`

**Comment by issie81** [comment]
@chiptus 

if you read my edit2 section you see i fixed that issue, can you confirm this is good values?

ok running ./tezos-client client show gives

Warning: no config file at /home/xx/.tezos-client/config,
displaying the default configuration.
{ "base_dir": "/home/xx/.tezos-client", "node_addr": "localhost",
"node_port": 8732, "tls": false, "web_port": 8080, "confirmations": 0 }

so my current config is

{ "base_dir": "/home/xx/.tezos-client", "node_addr": "localhost",
"node_port": 8732, "tls": false, "web_port": 8080, "confirmations": 0 }

**Comment by emilnygaard** [comment]
That was it for me! It was trying to process a cycle that had no rewards and no payouts, that's what threw the error:
`backerei: app/Payout.hs:56:19-92: Irrefutable pattern failed for pattern [thisCycle]`

**Comment by issie81** [comment]
@chiptus

Yeah off course the node is on the machine, since 2 cycles there are new delegees ( i dont promote until i nailed the issue) so guess have ro wait and run continues run till gets payout..

You change cycle per payment but who sends the payment you by cli of backerei

Wish Bakcerei would give more input what is going on

**Comment by Trappist8** [comment]
> `backerei: app/Payout.hs:56:19-92: Irrefutable pattern failed for pattern [thisCycle]`

I have seen this same error while rewards and payouts were pending on the blockchain. I am having the same exact issue as "issie81".

**Comment by issie81** [comment]
seems like massive issue's with Backerei, what are we doing wrong @adrianbrink devs?

**Comment by issie81** [comment]
i think i have backerei good now lets wait for the first payout:)
i start baking cycle 65 so payout is in cycle 73? 7+7?

**Comment by cwgoes** [comment]
Closing this issue since everything seems to be resolved; reopen if any errors recur.
