### ISSUE TITLE
I encountered an error while performing the installation

### ISSUE THREAD

**Issue by focusshell** [cryptiumlabs/backerei#20]
![image](https://user-images.githubusercontent.com/42060860/50532666-75ec6e00-0b57-11e9-92e3-6d033cb0e309.png)
When I followed Makfile's steps, I encountered an unknown error. How should I solve it?

**Comment by focusshell** [comment]
![image](https://user-images.githubusercontent.com/42060860/50532706-2f4b4380-0b58-11e9-87f7-e4152cf413fe.png)
Is this error a function error?

**Comment by cwgoes** [comment]
That's a Stack problem, not related to Backerei (Stack is a Haskell build tool), perhaps file an issue on their repo (first check that you have the latest software version).
