### ISSUE TITLE
Deviation of bonus calculation data

### ISSUE THREAD

**Issue by focusshell** [cryptiumlabs/backerei#22]
The dividend data calculated by your program is about 1.5 different from the data calculated manually by us. How can we solve this problem?

**Comment by cwgoes** [comment]
Likely they differ because `backerei` calculates idealized rewards as opposed to realized ones.

Without knowing how you're calculating data manually, it's difficult to answer your question precisely.

**Comment by chiptus** [comment]
I also see a difference between what backerei shows us to what tzscan shows

**Comment by focusshell** [comment]
![image](https://user-images.githubusercontent.com/42060860/50579041-51a4d000-0e7c-11e9-9c4b-cd820b84d9bf.png)

**Comment by focusshell** [comment]
> > 我也看到了backerei向我们展示tzscan所展示的内容之间的区别。
> 
> 是的，TzScan将显示已实现的奖励，因此Backerei显示（和支付）的值通常会更高。
> 
> 改变代码来代替支付实现的奖励很容易; 很乐意接受一个PR，它补充说作为配置选项。
![image](https://user-images.githubusercontent.com/42060860/50579065-79943380-0e7c-11e9-9d0e-c6972612dd82.png)

**Comment by focusshell** [comment]
> > 我也看到了backerei向我们展示tzscan所展示的内容之间的区别。
> 
> 是的，TzScan将显示已实现的奖励，因此Backerei显示（和支付）的值通常会更高。
> 
> 改变代码来代替支付实现的奖励很容易; 很乐意接受一个PR，它补充说作为配置选项。

![image](https://user-images.githubusercontent.com/42060860/50579075-8add4000-0e7c-11e9-96d0-026029cb3741.png)
I made a mistake when I executed the dividend command of the program. How can I sort out this mistake?

**Comment by focusshell** [comment]
We are very anxious for you to answer this question.

**Comment by focusshell** [comment]
![image](https://user-images.githubusercontent.com/42060860/50627184-44b3d980-0f6d-11e9-9001-c859aed0110e.png)
I made a mistake when I executed the dividend command of the program. How can I sort out this mistake?

**Comment by cwgoes** [comment]
> I made a mistake when I executed the dividend command of the program. How can I sort out this mistake?

This doesn't seem related to payment calculations.

Check that `tezos-client` can be executed on your shell (try running that command manually).

**Comment by focusshell** [comment]
How to run it manually, our tezo-client can be executed in the shell

**Comment by focusshell** [comment]
![image](https://user-images.githubusercontent.com/42060860/50735546-d9c40600-11eb-11e9-9c46-ac8566efb854.png)
When we entered the password, a new error occurred.

**Comment by focusshell** [comment]
When we entered the password, a new error occurred.
![image](https://user-images.githubusercontent.com/42060860/50737862-74324280-1208-11e9-9942-b7c693a48616.png)

**Comment by cwgoes** [comment]
That sounds like you need to specify a different config file in `backerei.yaml` (which is passed to `tezos-client` using the `-c` flag).

**Comment by focusshell** [comment]
> That sounds like you need to specify a different config file in `backerei.yaml` (which is passed to `tezos-client` using the `-c` flag).

What should I do?
How do I specify the path of other configuration files in the configuration file, and what is the additional configuration path specified?

**Comment by focusshell** [comment]
How to write this config file

**Comment by focusshell** [comment]
![image](https://user-images.githubusercontent.com/42060860/50880026-fa70a380-1417-11e9-8e3c-0c5d3a86e179.png)
After we changed config, we found a new error

**Comment by chiptus** [comment]
@focusshell you were commenting on a wrong issue.

Can we re-open this, as the original issue is still a problem?

**Comment by focusshell** [comment]
@chiptus 
We have a new problem.

**Comment by cwgoes** [comment]
I don't think there are any actionable items here. If you want to add alternative fee calculation methods feel free to submit a pull request. I answered the question about mempool filtering here - https://github.com/cryptiumlabs/backerei/issues/21#issuecomment-453850987.
