### ISSUE TITLE
rejected by the mempool pre filter 

### ISSUE THREAD

**Issue by focusshell** [cryptiumlabs/backerei#25]
![image](https://user-images.githubusercontent.com/42060860/50885447-b1751b00-1428-11e9-9e0c-c143830eb780.png)
We solved the config problem, but now we have a new memory problem?

**Comment by cwgoes** [comment]
Either change your Tezos node configuration to accept zero-fee transactions, or modify the Backerei source to set a non-zero fee (as in https://github.com/cryptiumlabs/backerei/compare/cwgoes/default-fee).

**Comment by focusshell** [comment]
After I changed the file according to your prompt, it showed success after execution, but did not perform the action, and the browser did not display the transaction.

![c39ffc03138d3284ec54e72610a9824](https://user-images.githubusercontent.com/42060860/50911643-46006d00-146b-11e9-8a83-3ea784969941.png)

**Comment by focusshell** [comment]
![c39ffc03138d3284ec54e72610a9824](https://user-images.githubusercontent.com/42060860/50911768-8c55cc00-146b-11e9-9fbc-ef98aff74560.png)
