### ISSUE TITLE
Error while applying operation. --no-dry-run

### ISSUE THREAD

**Issue by MarimbaTz** [cryptiumlabs/backerei#26]
New machine. New node. New Bäckerei install.
With the following steps:
- the install is on the right $PATH
- the payout address is revealed
- the client path is changed form the “default” to the right one inside /home/xxxx/tezos/tezos-client/
- the Tezos node is initialised and I have the config file inside the .tezos-client folder
- the tezos node is set to accept 0 fees
- Bäckerei is modified to execute non 0 fees transaction as shown here: https://github.com/cryptiumlabs/backerei/compare/cwgoes/default-fee
- the node is tested to accept incoming and outgoing transactions.

All I get is this message:
![false-positive](https://user-images.githubusercontent.com/46961225/51607361-15194100-1f1d-11e9-95ae-4e131654f2a8.gif)

**Comment by MarimbaTz** [comment]
`tezos-node` is printing this error:
Jan 23 15:40:36 - prevalidator.NxxXxxxxxxx.PsxxXxxxxxxx(1): injecting operation xxXxxxxxxxxxxxxxxx
Jan 23 15:40:36 - prevalidator.NxxXxxxxxxx.PsxxXxxxxxxx(1): Pushed: 2019-01-23T13:40:36Z, Treated: 2019-01-23T13:40:36Z, Failed: 2019-01-23T13:40:36Z
Jan 23 15:40:36 - prevalidator.xxXxxxxxxx.PsxxXxxxxxxx(1): Error while applying operation xxXxxxxxxxxxxxxx

**Comment by cwgoes** [comment]
I suggest looking for more details from your node logs - perhaps your node is configured to require a higher fee, perhaps the address from which you're trying to send does not have sufficient funds, or perhaps the `payments` account is not the manager of the account from which you are trying to pay.

**Comment by issie81** [comment]
run this command should fix your issue

./tezos-client rpc post /chains/main/mempool/filter with '{ "minimal_fees": "0", "minimal_nanotez_per_gas_unit": "0", "minimal_nanotez_per_byte": "0" }'

**Comment by MarimbaTz** [comment]
I set the node to accept 0 fee transactions already.  The issue comes after setting the 0 fee by running the "0 fee" command.
Also I have sufficient funds in the `payments` account and I'm sure the `payments` account is rightfully managed.

**Comment by issie81** [comment]
i see i have the same issue.. i got positive message but funds not send, awaiting devs for solution then

**Comment by cwgoes** [comment]
Closing in favor of https://github.com/cryptiumlabs/backerei/issues/27.
