### ISSUE TITLE
Write a how-to install and run Bäckerei guide

### ISSUE THREAD

**Issue by awasunyin** [cryptiumlabs/backerei#3]
Some people have had issues installing and running. I will publish a blogpost about this

**Comment by DreamXzxy** [comment]
Looking forward to it.

**Comment by gaia** [comment]
do we need to install Stack and Hlint?

**Comment by cwgoes** [comment]
@gaia See https://github.com/cryptiumlabs/backerei/issues/7#issuecomment-439413929. I have clarified this in `README.md`.

**Comment by goodpen** [comment]
when you write manual how install ?

**Comment by cwgoes** [comment]
The [usage section of the README](https://github.com/cryptiumlabs/backerei#usage) should serve this purpose for the time being.
