### ISSUE TITLE
Adjustments for Babylon2.0 / Babylon2.0.1

### ISSUE THREAD

**Issue by awasunyin** [cryptiumlabs/backerei#43]
Babylon introduces some changes into the rewards model for endorsements. This affects the rewards calculation tool in Bäckerei.

Assuming that Babylon will pass the current voting period, which will conclude in ~12 days: https://tzscan.io/proposals

**Comment by cwgoes** [comment]
There are blocks with strange baker rewards, e.g.:

`tezos-client rpc get /chains/main/blocks/BL2yy8cjwRrJ4ctvgAgLDBAF18uyDNAcWuzd5CRSueafn4ShxZr/metadata`

==>

```json
{"balance_updates":
[ { "kind": "contract",
"contract": "tz1PriNQyDC7d5ccPAD96ugujYy5YbdGLdQ5",
"change": "-512000000" },
{ "kind": "freezer", "category": "deposits",
"delegate": "tz1PriNQyDC7d5ccPAD96ugujYy5YbdGLdQ5", "cycle": 160,
"change": "512000000" },
{ "kind": "freezer", "category": "rewards",
"delegate": "tz1PriNQyDC7d5ccPAD96ugujYy5YbdGLdQ5", "cycle": 160,
"change": "7200000" } ] }
```

7.2 XTZ?!
