### ISSUE TITLE
Provide guidance on building as a Nix derivation

### ISSUE THREAD

**Issue by clacke** [cryptiumlabs/backerei#5]
As part of fractalide/fractalpools#54 I would like to build Bäckerei as a Nix derivation, so that I can use it from within a NixOS service.

I've managed to build it with `stack --nix ...`, but unfortunately the Nix wrapper around it, `haskell.lib.buildStackProject`, can only be used for setting up a build environment, not for actually building it within Nix, for NixOS/nixpkgs#32005 reasons.

I'm currently trying [stack2nix](/input-output-hk/stack2nix), and it's generating a `default.nix`, but I'm having some dependency issues. Still figuring out how it's supposed to work.

**Comment by cwgoes** [comment]
Great idea, will take a look at when I have time - if you do get it working, please submit a PR, we'll gladly merge.
