### ISSUE TITLE
What happens in case of overdelegation

### ISSUE THREAD

**Issue by denver-s** [cryptiumlabs/backerei#52]
I just don't get what happens in case of overdelegation, in terms of payouts handling.

If a baker's capacity is 100,000 XTZ and has 3 delegators

- A with 50,000 XTZ
- B with 40,000 XTZ
- C with 20,000 XTZ

So 110,000 XTZ delegated. Will the extra 10,000 XTZ excluded from the calculation of the rewards for delegator C? What if someone else delegates to the baker?

**Comment by cwgoes** [comment]
Backerei does not take baker balance or bond requirements into account - if you have insufficient self-bond to bake or endorse, `backerei` will still calculate the rewards which you would have received in the ideal case, and pay delegators accordingly (which might mean that you lose money, if you were severely overdelegated).

If you would prefer a different behaviour as an option, PRs are welcome.
