### ISSUE TITLE
endorsement rewards inaccurate after Carthage changes ?

### ISSUE THREAD

**Issue by nicolasochem** [cryptiumlabs/backerei#59]
Hi,
I am observing that the actual endorsement rewards are too high since the Carthage code changes.

Example using Cryptium's address and doing the calculations for block 209. Calculating both the expected rewards and actual rewards on the new codebase, I see the following:

```
nochem@peck ~/workspace/backerei () $ ./backerei payout                                                                                                                                                             
Enter source account password:                                                                                                                                                                                      
Updating DB with actual earnings for cycle 209...                                                                                                                                                                   
Expected / actual endorsement rewards (plus self-baked insurance) for cycle 209: 6023.750000 / 8929.375000                                                                                                          
Lost endorsement rewards due to other-baker downtime for cycle 209: -2905.625000                                                                                                                                    
Expected / actual baking rewards (plus self-baked insurance) for cycle 209: 5520.000000 / 5253.750000                                                                                                               
Lost baking rewards due to missing endorsements for cycle 209: 266.250000                                                   
```

Cross-checking with [tzstats info](https://tzstats.com/tz1eEnQhbwf6trb8Q8mPb2RaPkNk2rN7BKi8), I see that the actual baking rewards match, but the endorsement rewards for cycle 209 should be 5,932.499927 XTZ, not 8929.375000XTZ.

I have the same issue with my baker. The "lost endorsment rewards due to other-baker downtime" are negative.

**Comment by cwgoes** [comment]
As we pay five cycles delayed (when rewards are unlocked), I haven't had an opportunity to check this until now - thanks, you are quite correct, there was a typo, fixed on `master` now & the values should match TzStats, more or less (there is still some small discrepancy, not sure why).
