### ISSUE TITLE
Backerei payout : connection refused

### ISSUE THREAD

**Issue by Resilioh** [cryptiumlabs/backerei#6]
Hi,

Thank you for sharing your batch payment system.
Not an expert, just followed the installation guide (stack, hLint). Everything is fine.
Backerei config file is initialized. However, when I run the command line "backerei payout", it give me that : "ConnectionFailure Network.stocket.connect: <socket 11>: does not exist (connection refused)"

I'm running the script on a Ubuntu 18.04, with VirtualBox, on the Tezos alphanet with Docker. After some researches, I found that it may be VirtualBox the problem and VirtualBox Fusion should fix that.
Did someone ever had this problem ?

Thanks

**Comment by adrianbrink** [comment]
Could you post the `backerei.yaml` file and the exact command that you ran.

**Comment by Resilioh** [comment]
**Content of my `backerei.yaml` file :** 

fromAddress : tz1… 
fromAccountName : myBaker 
databasePath : /home/user/.backerei.json
 fees :
 	denominator : 10
 	numerator : 1 
cycleLenght : 4096
 clientPath : /var/lib/docker/volumes/alphanet_client_data/_data 
clientConfigFile : /var/lib/docker/volumes/alphanet_client_data/_data/config 
startingCycle 87 
host : 127.0.0.1 
snapshot interval : 256 
baker address : tz1… 
port : 8732

**Command line I ran :** 
sudo ./backerei payout 
(or just "backerei payout" works too)

Do you notice something wrong ? Thank you

**Comment by cwgoes** [comment]
@Resilioh Are you sure your Docker container (looks like you're running Tezos in Docker) is bound to `127.0.0.1:8732`? You'll have to configure it to do so (with `--net=host` or an explicit port mapping).

**Comment by cwgoes** [comment]
Closing for now, please reopen if you continue to experience issues.
