### ISSUE TITLE
Backerei 404

### ISSUE THREAD

**Issue by thearchitectnyc** [cryptiumlabs/backerei#60]
I am running a local node and attempting to use backerei 
commands like backerei monitor and backerei init appear to work
However, backerei payout always throws this exception:
```
$ backerei payout
Enter source account password: 
Creating new DB in file /home/username/.backerei.json...
Updating DB with estimates for cycle 212...
backerei: VanillaHttpException (HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 8732
  secure               = False
  requestHeaders       = []
  path                 = "/chains/main/blocks/BMEWWcDvaehAzuCNmkrD2r3cBJpNJ9j4jABjS6qND1YmRpDCHJM~27655/header"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutMicro 600000000
  requestVersion       = HTTP/1.1
}
 (StatusCodeException (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("transfer-encoding","chunked")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}) ""))
```
This is probably a very simple fix. I have tried installing this on ubuntu server 18.04 and ubuntu desktop 19.10

**Comment by tzemanovic** [comment]
Can you confirm that you are running a full node? It looks like you may be running a rolling mode node, which doesn’t keep the data necessary for a baker

**Comment by adrianbrink** [comment]
You need to be running an archive node.

**Comment by thearchitectnyc** [comment]
I was running a full node. I stopped it an ran tezos-node reconstruct in order to turn it in to an archive node. I still get the 404 response.

**Comment by thearchitectnyc** [comment]
Update: I tried to convert the full node to an archive node using 
`tezos-node reconstruct`
However, the results were the same. I decided to completely rebuilt my node with 
`nohup ./tezos-node run --history-mode archive --rpc-addr 127.0.0.1 --connections 100 &`
Then I retried backerei and the 404 error stopped. 
Thank you for the feedback.

**Comment by cwgoes** [comment]
Glad you got it working, seems like this can be closed then.
