### ISSUE TITLE
Stack & Hlint

### ISSUE THREAD

**Issue by gaia** [cryptiumlabs/backerei#7]
do i need hlint & stack just for running backerei?

**Comment by cwgoes** [comment]
No, just Stack, and you only need Stack to build backerei (once backerei is installed you can remove it).

**Comment by focusshell** [comment]
![image](https://user-images.githubusercontent.com/42060860/50532647-2b6af180-0b57-11e9-8207-0244c9adf566.png)

**Comment by focusshell** [comment]
When I executed the installation command, an error occurred. How can I solve this mistake?

**Comment by cwgoes** [comment]
That looks like a Stack issue, not a Backerei one.
