### ISSUE TITLE
Baker Fee Per Delegate

### ISSUE THREAD

**Issue by gaia** [cryptiumlabs/backerei#9]
It would be useful to be able to set different fees for different delegates, or some delegates that should not get paid out (such as those that delegated under the minimum amount or when a baker delegates from their own stash)

**Comment by cwgoes** [comment]
Great idea - we don't presently do this, but would happily merge a PR which added per-delegate fees as a configurable option.

**Comment by gaia** [comment]
Thanks Chris. I will look further into this and see if I can send a PR.
